// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzW-vtMhXASXuW_I0mhv8ZiyTZQlxP_F8',
    appId: '1:181599164133:web:c69b618bee46e6ffc4e60c',
    messagingSenderId: '181599164133',
    projectId: 'veterinaria-a7fa7',
    authDomain: 'veterinaria-a7fa7.firebaseapp.com',
    storageBucket: 'veterinaria-a7fa7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdBPshgHL-Sl63Ptx71nxu--Kiy67vGdM',
    appId: '1:181599164133:android:7b0883387be41f75c4e60c',
    messagingSenderId: '181599164133',
    projectId: 'veterinaria-a7fa7',
    storageBucket: 'veterinaria-a7fa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbUY01otZ7HW4cS7N8kXuW5j50-82n2w4',
    appId: '1:181599164133:ios:dd382ae4b24f0168c4e60c',
    messagingSenderId: '181599164133',
    projectId: 'veterinaria-a7fa7',
    storageBucket: 'veterinaria-a7fa7.appspot.com',
    iosBundleId: 'com.codigocorrecto.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbUY01otZ7HW4cS7N8kXuW5j50-82n2w4',
    appId: '1:181599164133:ios:dd382ae4b24f0168c4e60c',
    messagingSenderId: '181599164133',
    projectId: 'veterinaria-a7fa7',
    storageBucket: 'veterinaria-a7fa7.appspot.com',
    iosBundleId: 'com.codigocorrecto.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzW-vtMhXASXuW_I0mhv8ZiyTZQlxP_F8',
    appId: '1:181599164133:web:004749146464bba0c4e60c',
    messagingSenderId: '181599164133',
    projectId: 'veterinaria-a7fa7',
    authDomain: 'veterinaria-a7fa7.firebaseapp.com',
    storageBucket: 'veterinaria-a7fa7.appspot.com',
  );
}
